name: "static analysis"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: [ ~1.8 ]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: ${{ matrix.terraform }}

      - uses: terraform-linters/setup-tflint@90f302c255ef959cbfb4bd10581afecdb7ece3e6 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - run: make fmt

      - run: make validate

      - run: make tflint

      - name: trivy config
        run: |
          cat >> ./trivy.yaml << EOF
          # see https://aquasecurity.github.io/trivy/latest/docs/references/configuration/config-file/ for reference
          exit-code: 1
          exit-on-eol: 1
          misconfiguration:
            terraform:
              exclude-downloaded-modules: true
          severity:
            - HIGH
            - CRITICAL
          scan:
            skip-dirs:
              - "**/.terraform/**/*"
          EOF

          cat ./trivy.yaml

      - uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # v0.24.0
        with:
          scan-type: 'config'
          hide-progress: false
          trivy-config: trivy.yaml
